[package]
name = "veloce-layout"
version = "0.1.0"
edition = "2021"
description = "Veloce terminal-UI framework (veloce-layout)"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
taffy = { workspace = true }
crossbeam-channel = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dependencies.veloce-core]
version = "0.1.0"
path = "../veloce-core"

[dev-dependencies]
proptest = { workspace = true }

[dev-dependencies.veloce-render]
path = "../veloce-render"
